# Generated by Django 3.0.7 on 2020-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200628_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
