# Generated by Django 3.0.7 on 2020-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
