# Generated by Django 3.0.7 on 2020-06-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200628_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='EU_35',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_35_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_36',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_36_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_37',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_37_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_38',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_38_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_39',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_39_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_40',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_40_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_41',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_41_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_42',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_42_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_43',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_43_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_44',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_44_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_45',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_45_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_46',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_46_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_47',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_47_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_48',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_48_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_49',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_49_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='EU_50',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=200),
        ),
    ]
